name: Deploy app
on:
  workflow_call:
  pull_request:
  push:
    branches:
      - "master"

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  ENV_FILE: ${{ env.BRANCH_NAME == 'master' && '.env.production' || '.env.development' }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'yarn'
      
      - name: Enable corepack
        run: corepack enable
      
      - name: Install dependencies
        run: yarn install --immutable

      - name: Fill .env.production values with secrets
        uses: Langsdorf/env-replace@v1.0.6
        if: github.ref == 'refs/heads/master'
        with:
          file: "./${{ env.ENV_FILE }}"
          replace-all: |
            VITE_PUBLIC_WC_PROJECT_ID=${{ secrets.VITE_PUBLIC_WC_PROJECT_ID }}
            VITE_PUBLIC_ETHEREUM_NODE_TOKEN=${{ secrets.VITE_PUBLIC_ETHEREUM_NODE_TOKEN }}
            VITE_PUBLIC_SEPOLIA_NODE_TOKEN=${{ secrets.VITE_PUBLIC_SEPOLIA_NODE_TOKEN }}

      - name: Build
        run: nuxt generate --dotenv ${{ env.ENV_FILE }}

      - name: Deploy to Cloudflare
        id: deploy-cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          command: pages deploy .output/public --project-name=pwn-staking-ui

      - name: Add comment to PR with deployed URL
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            Deployed on <${{ steps.deploy-cloudflare.outputs.pages-deployment-alias-url }}>!

      - name: Deploy to IPFS
        if: ${{ env.BRANCH_NAME }} == 'master'
        # TODO

      - name: Update DNSLink
        if: ${{ env.BRANCH_NAME }} == 'master'
        # TODO

